# Generated by Django 2.0.1 on 2018-01-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0003_auto_20180106_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='parent',
        ),
    ]
